import type { Config } from 'tailwindcss'

export default {
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': '#484949',
        'surface-container': '#1e2020',
        'on-error': '#690005',
        'on-secondary-fixed': '#1a1c1c',
        'elevated-bg': '#161616',
        'secondary-fixed': '#e3e2e2',
        'primary-container': '#0a0a0a',
        surface: '#121414',
        'on-primary-fixed-variant': '#474646',
        'on-tertiary': '#381385',
        'on-surface': '#e2e2e2',
        'on-primary-container': '#7b7979',
        'inverse-on-surface': '#2f3131',
        'surface-bright': '#37393a',
        'outline-variant': '#444748',
        'error-container': '#93000a',
        'surface-container-highest': '#333535',
        'on-background': '#e2e2e2',
        secondary: '#c7c6c6',
        'whatsapp-green': '#25D366',
        'on-tertiary-fixed': '#21005e',
        'surface-container-low': '#1a1c1c',
        'surface-variant': '#333535',
        'on-tertiary-fixed-variant': '#4f319c',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#e5e2e1',
        'surface-container-lowest': '#0c0f0f',
        'surface-dim': '#121414',
        'on-secondary-fixed-variant': '#464747',
        outline: '#8e9192',
        'secondary-fixed-dim': '#c7c6c6',
        tertiary: '#cebdff',
        'on-primary-fixed': '#1c1b1b',
        'tertiary-fixed': '#e8ddff',
        'inverse-primary': '#5f5e5e',
        'tertiary-container': '#0d0030',
        error: '#ffb4ab',
        'on-primary': '#313030',
        background: '#121414',
        'on-tertiary-container': '#8367d3',
        'on-secondary-container': '#b8b8b8',
        'tertiary-fixed-dim': '#cebdff',
        'border-default': 'rgba(255, 255, 255, 0.12)',
        'on-secondary': '#2f3131',
        'on-surface-variant': '#c4c7c7',
        'border-subtle': 'rgba(255, 255, 255, 0.08)',
        'surface-container-high': '#282a2b',
        'inverse-surface': '#e2e2e2',
        'card-bg': '#111111',
        primary: '#c9c6c5',
        'primary-fixed-dim': '#c9c6c5',
        'surface-tint': '#c9c6c5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1152px',
        'stack-sm': '0.5rem',
        gutter: '1.5rem',
        'stack-md': '1rem',
        'section-padding-y': '6rem',
        'stack-lg': '2rem',
      },
      fontFamily: {
        'body-md': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'display-hero-mobile': ['Syne', 'sans-serif'],
        button: ['Geist', 'sans-serif'],
        'display-hero': ['Syne', 'sans-serif'],
        'headline-lg': ['Syne', 'sans-serif'],
        'headline-md': ['Syne', 'sans-serif'],
        'label-mono': ['Geist Mono', 'monospace'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-hero-mobile': [
          '36px',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        button: ['15px', { lineHeight: '1', fontWeight: '500' }],
        'display-hero': [
          '64px',
          { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' },
        ],
        'headline-lg': [
          '48px',
          { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'label-mono': [
          '14px',
          { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' },
        ],
      },
      animation: {
        'marquee-bg': 'marquee-bg 40s linear infinite',
        'scroll': 'scroll 30s linear infinite',
      },
      keyframes: {
        'marquee-bg': {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-50%)' },
        },
        scroll: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(calc(-100% - 2rem))' },
        },
      },
    },
  },
  plugins: [],
} satisfies Config
